apiVersion: v2
name: Workload-Security
description: A Helm chart for Deploying ISecL-DC Workload Security Use case

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

#kubeVersion: "= 1.23"
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v5.1.0"

dependencies:
  - name: factory
    repository: file://../../lib/factory/ 
    version: 5.1.0
  - name: cleanup-secrets
    repository: file://../../jobs/cleanup-secrets/
    version: 5.1.0
  - name: wpm
    repository: file://../../jobs/wpm-aas-mgr/
    version: 5.1.0
  - name: cleanup-jobs
    repository: file://../../jobs/cleanup-jobs/
    version: 5.1.0
  - name: aasdb-cert-generator
    repository: file://../../jobs/aasdb-cert-generator/
    version: 5.1.0
  - name: hvsdb-cert-generator
    repository: file://../../jobs/hvsdb-cert-generator/
    version: 5.1.0
  - name: global-admin-generator
    repository: file://../../jobs/global-admin-generator/
    version: 5.1.0
  - name: nats-init
    repository: file://../../jobs/nats/
    version: 5.1.0
  - name: cms
    repository: file://../../services/cms/ 
    version: 5.1.0
  - name: aas
    repository: file://../../services/aas/ 
    version: 5.1.0
  - name: hvs
    repository: file://../../services/hvs/ 
    version: 5.1.0
  - name: trustagent
    repository: file://../../services/ta/
    version: 5.1.0
  - name: isecl-controller
    repository: file://../../services/isecl-controller/ 
    version: 5.1.0
  - name: ihub
    repository: file://../../services/ihub/ 
    version: 5.1.0
  - name: isecl-scheduler
    repository: file://../../services/isecl-scheduler/ 
    version: 5.1.0
  - name: nats
    repository: file://../../services/nats/
    version: 5.1.0
  - name: kbs
    repository: file://../../services/kbs/
    version: 5.1.0
  - name: wls
    repository: file://../../services/wls/
    version: 5.1.0
  - name: workload-agent
    repository: file://../../services/wla/
    version: 5.1.0

maintainers:
- name: JJ
  email: johnny.jacob@intel.com
- name: PraveenRaj R
  email: praveenrajr@intel.com
- name: rana19
  email: raghavender.nagarajan@intel.com
