{{- include "factory.headers" . }}
---
{{- include "factory.pvcConfigCommonSpec" . }}
  storageClassName: manual
  accessModes:
     {{ toYaml .Values.storage.hostPath.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.hostPath.configSize }}
