apiVersion: v2
appVersion: v5.1.0
dependencies:
- name: factory
  repository: file://../../lib/factory/
  version: 5.1.0
description: A Helm chart for Installing ISecL-DC Certificate Management Service
name: cms
type: application
version: v5.1.0
