apiVersion: v2
appVersion: v5.1.0
dependencies:
- name: factory
  repository: file://../../lib/factory/
  version: 5.1.0
- name: cleanup-secrets
  repository: file://../../jobs/cleanup-secrets/
  version: 5.1.0
- name: cleanup-jobs
  repository: file://../../jobs/cleanup-jobs/
  version: 5.1.0
- name: aasdb-cert-generator
  repository: file://../../jobs/aasdb-cert-generator/
  version: 5.1.0
- name: global-admin-generator
  repository: file://../../jobs/global-admin-generator/
  version: 5.1.0
- name: hvsdb-cert-generator
  repository: file://../../jobs/hvsdb-cert-generator/
  version: 5.1.0
- name: cms
  repository: file://../../services/cms/
  version: 5.1.0
- name: aas
  repository: file://../../services/aas/
  version: 5.1.0
- name: nats-init
  repository: file://../../jobs/nats/
  version: 5.1.0
- name: hvs
  repository: file://../../services/hvs/
  version: 5.1.0
- name: nats
  repository: file://../../services/nats/
  version: 5.1.0
- name: trustagent-aas-manager
  repository: file://../../jobs/tagent-aas-mgr
  version: 5.1.0
description: A Helm chart for Deploying ISecL-DC Trusted Workload Placement - Control
  Plane Use case
maintainers:
- email: johnny.jacob@intel.com
  name: JJ
- email: praveenrajr@intel.com
  name: PraveenRaj R
- email: raghavender.nagarajan@intel.com
  name: rana19
name: Trusted-Workload-Placement-Control-Plane
type: application
version: v5.1.0
