{{- include "factory.headers" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cleanup-jobs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cleanup-jobs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "cleanup-jobs.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.cleanupJobsInit | nindent 8 }}
      serviceAccountName: {{ .Release.Namespace }}-jobs
      restartPolicy: Never
      containers:
        - name: cleanup-jobs
          image: bitnami/kubectl:1.23
          imagePullPolicy: Always
          securityContext:
            {{- toYaml .Values.securityContext.cleanupJobs | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo starting &&
              kubectl delete jobs --all -n {{ .Release.Namespace }}
